### PR TITLE
Alamofire 5 and Swift 5.2

### PR DESCRIPTION
**Pull request by robertjanetzko**
works with carthage, but I have no expierience with swift package manager

### CODE REVIEW

**Comment by ozgur** [comment]
@mxcl Any update on getting this merged?

**Comment by mxcl** [comment]
Like I said in the other thread it’s impossible to merge this without breaking API stability.

**Comment by robertjanetzko** [comment]
as there are 3 open pull requests for this topic with mostly the same changes, i think someone should find a solution how this can be handled...

**Comment by mxcl** [comment]
A possible solution is a new podspec subspec for Alamofire 5 on the PromiseKit repo. PR welcome.

Honestly though the code is so minimal for this extension you may as well just embed it in your app.

I do not have the time currently to maintain these sort of aspects of PromiseKit, it's intense work that doesn’t pay off for many.

But yes we cannot bump Alamofire without breaking existing apps that use Alamofire 4.

**Comment by ozgur** [comment]
For those who are using **PMKAlamofire** through Carthage, you can add the following into your `Cartfile`:
```
github "ozgur/PMKAlamofire" "master"
```
It is Alamofire 5.x compliant.

**Comment by mxcl** [comment]
Released 4.0.0

**Pull request closed without merging**
