### PR TITLE
Update to Alamofire 5 and Swift 5

### PR DESCRIPTION
**Pull request by larsschwegmann**
Hi!
I've updated PMKAlamofire to work with Alamofire 5 and Swift 5. My applications depends on this package and would love to see it updated so I don't need to use my custom fork anymore.

There are a few breaking changes:
I had to update the Deployment targets in order to fit the Alamofire 5 deployment targets. I also had to remove the responsePropertyList() functions, as Alamofire apparently dropped support for that functionality.

### CODE REVIEW

**Comment by larsschwegmann** [comment]
Alamofire 5 requires Swift 5 or higher, thus I expect the CI build for older versions to fail

**Comment by larsschwegmann** [comment]
Alright, so Travis seems to fail at the `pod lint` stage because the Podspec it uses comes from the main [PromiseKit repo](https://github.com/mxcl/PromiseKit/blob/master/.github/PromiseKit.podspec) which still points to Alamofire 4. I have no idea how to fix the CI build.

Help would be appreciated. Thank you! 😄

**Comment by mxcl** [comment]
> Alright, so Travis seems to fail at the pod lint stage because the Podspec it uses comes from the main PromiseKit repo which still points to Alamofire 4. I have no idea how to fix the CI build.

Yeah this is problematic, and justifies that for PMK 7 I split the pod. I think we'll just have to remove the lint step for this repo’s major bump.

**Comment by RemiRodrigues** [comment]
Hello 👋

As long as this PR is not on Master for CI reasons, could you create a branch that use this PR for those who work with Alamofire > 5.0.0 and love PromiseKit 😊

Thank you

**Comment by hactar** [comment]
Any update on this? This packet and its dependencies are the only thing preventing us from being a "swift 5" only app.

**Comment by lmcd** [comment]
Any updates with this?

**Comment by kacper1703** [comment]
Hi, I would love to update Alamofire to 5.0 but this dependency prevents us from using it. Please consider updating! 🙏

**Comment by mxcl** [comment]
Released 4.0.0

**Pull request closed without merging**
