### PR TITLE
ability to change queue (for server side swift)

### PR DESCRIPTION
**Pull request by k1313**

### CODE REVIEW

**Comment by mxcl** [comment]
Why do you need this?

**Comment by k1313** [comment]
Not working with main queue (on perfect framework)

**Comment by mxcl** [comment]
OK, well irrelevant of my question, I guess we should expose the same interface as Alamofire does.

**Comment by mxcl** [comment]
Closed by b1d6b23a35b5fc08bf69ca8681315523ce37661e, thanks!

**Pull request closed without merging**
